# Make sure only the cluster admin is able to execute Memtierd commands
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-exec-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-exec-rolebinding
  namespace: default
subjects:
- kind: User
  name: <cluster-admin-username>   # Replace with the actual cluster admin username
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: allow-exec-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-memtier
  labels:
    app: pod-memtier
spec:
  hostPID: true
  containers:
  - name: pod-memtier
    image: <your registry>/memtier-nri
    imagePullPolicy: Always
    securityContext:
      privileged: true
    volumeMounts:
      - name: nri-socket
        mountPath: /var/run/nri/nri.sock
      - name: host-volume
        mountPath: /host
      - name: host-bitmap
        mountPath: /sys/kernel/mm/page_idle/bitmap
      - name: memtierd-data
        mountPath: /tmp/memtierd
  volumes:
    - name: nri-socket
      hostPath:
        path: /var/run/nri/nri.sock
    - name: host-volume
      hostPath:
        path: /
    - name: host-bitmap
      hostPath:
        path: /sys/kernel/mm/page_idle/bitmap
    - name: memtierd-data
      hostPath:
        path: /tmp/memtierd